server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
          defaultZone: http://peer2:8762/eureka
defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka